#!/usr/bin/env bash

declare -A clock_icons

clock_icons=(
  [0]="󱑊"  # 12:00
  [1]="󱐿"  # 1:00
  [2]="󱑀"  # 2:00
  [3]="󱑁"  # 3:00
  [4]="󱑂"  # 4:00
  [5]="󱑃"  # 5:00
  [6]="󱑄"  # 6:00
  [7]="󱑅"  # 7:00
  [8]="󱑆"  # 8:00
  [9]="󱑇"  # 9:00
  [10]="󱑈" # 10:00
  [11]="󱑉" # 11:00
)

current_hour=$(date +"%I")
current_hour=$((10#$current_hour % 12))
echo "${clock_icons[$current_hour]}"
