[settings]
experimental = true
auto_install = true
lockfile = true

[settings.npm]
package_manager = "bun"

[tool_alias]
nvim12 = "neovim@0.12"

[tools]
aws-cli = { version = "2.34.37", symlink_bins = "true" }
bat = "0.26.1"
bottom = "0.12.3"
bun = "1.3.13"
"cargo:taws" = "1.2.1"
crane = "0.21.5"
crossplane-cli = "2.2.1"
deno = "2.7.13"
docker-cli = "29.4.3"
dotnet = "10.0.201"
dotnet-core = "10.0.203"
fd = "10.4.2"
flux2 = "2.8.6"
fzf = "0.72.0"
gh = "2.91.0"
go = "1.26.2"
"go:github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer" = "0.7.4"
"go:github.com/charmbracelet/crush" = "0.62.1"
"go:golang.org/x/tools/gopls" = "0.21.1"
"aqua:charmbracelet/gum" = "0.17.0"
helm = "4.1.4"
helm-ls = "0.5.4"
java = "26.0.0"
k9s = "0.50.18"
kubectl = "1.36.0"
lazygit = "0.61.1"
lua-language-server = "3.18.2"
neovim = "0.11.7"
node = "25.9.0"
npm = "11.13.0"
"npm:@anthropic-ai/claude-code" = "2.1.120"
"npm:@astrojs/language-server" = "2.16.6"
"npm:@playwright/cli" = "0.1.10"
"npm:@playwright/mcp" = "0.0.73"
"npm:@slidev/cli" = "52.14.2"
"npm:@sveltejs/mcp" = "0.1.22"
"npm:@upstash/context7-mcp" = "2.2.1"
"npm:@vtsls/language-server" = "0.3.0"
"npm:agent-browser" = "0.26.0"
"npm:bash-language-server" = "5.6.0"
"npm:ctx7" = "0.4.0"
"npm:opencode-ai" = "1.15.4"
"npm:prettier" = "3.8.3"
"npm:skills" = "1.5.1"
"npm:svelte-language-server" = "0.17.30"
oh-my-posh = "29.10.0"
packer = "1.15.3"
pnpm = "10.33.2"
pre-commit = "4.6.0"
pulumi = "3.232.0"
python = "3.14.4"
ripgrep = "15.1.0"
ruff = "0.15.12"
rust = "1.95.0"
rust-analyzer = "2026-03-23"
shellcheck = "0.11.0"
sops = "3.12.2"
stylua = "2.5.2"
terraform = "1.14.9"
terraform-ls = "0.38.6"
tmux = "3.6a"
tree-sitter = "0.26.9"
trufflehog = "3.95.3"
usage = "3.2.1"
uv = "0.11.8"
viddy = "1.3.0"
yazi = "26.1.22"
yq = "4.53.2"
zoxide = "0.9.9"
golangci-lint = "2.12.2"
golangci-lint-langserver = "0.0.12"
yamlfmt = "0.21.0"
