#:schema https://mise.en.dev/schema/mise.json
[settings]
experimental = true
auto_install = true
lockfile = true

[shell_alias]
helm3 = "mise x helm@3 -- helm"

[settings.npm]
package_manager = "bun"

[tool_alias]
nvim12 = "neovim@0.12"

[tools.docker-compose]
version = "5.1.4"
postinstall = 'mkdir -p "$HOME/.docker/cli-plugins" && ln -sf "$(which docker-cli-plugin-docker-compose)" "$HOME/.docker/cli-plugins/docker-compose"'

[tools."github:docker/buildx"]
version = "0.34.1"
bin = "docker-buildx"
postinstall = 'mkdir -p "$HOME/.docker/cli-plugins" && ln -sf "$(which docker-buildx)" "$HOME/.docker/cli-plugins/docker-buildx"'

[tools.aws-cli]
version = "2.34.49"
symlink_bins = "true"

[tools.podman]
version = "5.8.2"
bin = "podman"

[tools]
"aqua:charmbracelet/gum" = "0.17.0"
"cargo:taws" = "1.2.1"
"github:uutils/coreutils" = "0.8.0"
"github:uutils/findutils" = "0.8.0"
"github:uutils/sed" = "0.1.1"
"go:github.com/awslabs/eks-node-viewer/cmd/eks-node-viewer" = "0.7.4"
"go:github.com/charmbracelet/crush" = "v0.70.0"
"go:golang.org/x/tools/gopls" = "v0.22.0"
"npm:@anthropic-ai/claude-code" = "2.1.150"
"npm:@astrojs/language-server" = "2.16.9"
"npm:@playwright/cli" = "0.1.13"
"npm:@playwright/mcp" = "0.0.75"
"npm:@slidev/cli" = "52.15.2"
"npm:@sveltejs/mcp" = "0.1.23"
"npm:@upstash/context7-mcp" = "2.3.0"
"npm:@vtsls/language-server" = "0.3.0"
"npm:agent-browser" = "0.27.0"
"npm:bash-language-server" = "5.6.0"
"npm:ctx7" = "0.4.4"
"npm:opencode-ai" = "1.15.10"
"npm:prettier" = "3.8.3"
"npm:skills" = "1.5.7"
"npm:svelte-language-server" = "0.18.0"
bat = "0.26.1"
bottom = "0.12.3"
bun = "1.3.14"
crane = "0.21.6"
crossplane-cli = "2.2.1"
deno = "2.7.14"
docker-cli = "29.5.1"
dotnet = "10.0.201"
dotnet-core = "10.0.300"
fd = "10.4.2"
flux2 = "2.8.7"
fzf = "0.72.0"
gh = "2.92.0"
go = "1.26.3"
golangci-lint = "2.12.2"
golangci-lint-langserver = "0.0.12"
helm = "4.2.0"
helm-ls = "0.5.4"
java = "26.0.0"
k9s = "0.50.18"
kubectl = "1.36.1"
lazygit = "0.61.1"
lua-language-server = "3.18.2"
neovim = "0.12.2"
node = "25.9.0"
npm = "11.15.0"
oh-my-posh = "29.14.0"
packer = "1.15.3"
pnpm = "11.2.2"
pre-commit = "4.6.0"
pulumi = "3.241.0"
python = "3.14.5"
ripgrep = "15.1.0"
ruff = "0.15.13"
rust = "1.95.0"
rust-analyzer = "2026-03-23"
shellcheck = "0.11.0"
shfmt = "3.13.1"
sops = "3.13.1"
stylua = "2.5.2"
terraform = "1.15.3"
terraform-ls = "0.38.6"
tmux = "3.6a"
tree-sitter = "0.26.9"
trufflehog = "3.95.3"
usage = "3.3.0"
uv = "0.11.15"
viddy = "1.3.0"
yamlfmt = "0.21.0"
yazi = "26.5.6"
yq = "4.53.2"
zoxide = "0.9.9"
"github:atanunq/viu" = "1.6.1"
dive = "0.13.1"
taplo = "0.10.0"
"npm:@rynfar/meridian" = "1.42.1"
